In [72]:
%pip install kagglehub
import kagglehub

# Download latest version
path = kagglehub.dataset_download("kaggle/sf-salaries")
print("Path to dataset files:", path)

Path to dataset files: /home/pyodide/.cache/kagglehub/datasets/kaggle/sf-salaries/versions/5

In [73]:
import os
import pandas as pd

files = os.listdir(path)
print("Files in dataset:", files)

# Use os.path.join to pass the full file path
data = pd.read_csv(os.path.join(path, files[0]),low_memory=False)

Files in dataset: ['Salaries.csv', 'database.sqlite']

In [8]:
data.info

<bound method DataFrame.info of             Id       EmployeeName  \
0            1     NATHANIEL FORD
1            2       GARY JIMENEZ
2            3     ALBERT PARDINI
3            4  CHRISTOPHER CHONG
4            5    PATRICK GARDNER
...        ...                ...
148649  148650      Roy I Tillery
148650  148651       Not provided
148651  148652       Not provided
148652  148653       Not provided
148653  148654          Joe Lopez

                                              JobTitle       BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY     167411.18
1                      CAPTAIN III (POLICE DEPARTMENT)     155966.02
2                      CAPTAIN III (POLICE DEPARTMENT)     212739.13
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC       77916.0
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)      134401.6
...                                                ...           ...
148649                                       Custodian          0.00
148650                                    Not provided  Not Provided
148651                                    Not provided  Not Provided
148652                                    Not provided  Not Provided
148653                      Counselor, Log Cabin Ranch          0.00

         OvertimePay      OtherPay      Benefits   TotalPay  TotalPayBenefits  \
0                0.0     400184.25           NaN  567595.43         567595.43
1          245131.88     137811.38           NaN  538909.28         538909.28
2          106088.18       16452.6           NaN  335279.91         335279.91
3           56120.71      198306.9           NaN  332343.61         332343.61
4             9737.0     182234.59           NaN  326373.19         326373.19
...              ...           ...           ...        ...               ...
148649          0.00          0.00          0.00       0.00              0.00
148650  Not Provided  Not Provided  Not Provided       0.00              0.00
148651  Not Provided  Not Provided  Not Provided       0.00              0.00
148652  Not Provided  Not Provided  Not Provided       0.00              0.00
148653          0.00       -618.13          0.00    -618.13           -618.13

        Year  Notes         Agency Status
0       2011    NaN  San Francisco    NaN
1       2011    NaN  San Francisco    NaN
2       2011    NaN  San Francisco    NaN
3       2011    NaN  San Francisco    NaN
4       2011    NaN  San Francisco    NaN
...      ...    ...            ...    ...
148649  2014    NaN  San Francisco     PT
148650  2014    NaN  San Francisco    NaN
148651  2014    NaN  San Francisco    NaN
148652  2014    NaN  San Francisco    NaN
148653  2014    NaN  San Francisco     PT

[148654 rows x 13 columns]>

In [9]:
data.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [10]:
data.tail()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT

In [12]:
data.shape

(148654, 13)

In [13]:
data.shape[0]

148654

In [14]:
data.shape[1]

13

In [17]:
data.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [19]:
data.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='str')

In [21]:
data=data.drop(['Id','Notes', 'Agency','Status'],axis=1)

In [22]:
data

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014
148650,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014

In [23]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [24]:
data.describe()

            TotalPay  TotalPayBenefits           Year
count  148654.000000     148654.000000  148654.000000
mean    74768.321972      93692.554811    2012.522643
std     50517.005274      62793.533483       1.117538
min      -618.130000       -618.130000    2011.000000
25%     36168.995000      44065.650000    2012.000000
50%     71426.610000      92404.090000    2013.000000
75%    105839.135000     132876.450000    2014.000000
max    567595.430000     567595.430000    2014.000000

In [25]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [26]:
data['EmployeeName'].head(5)

0       NATHANIEL FORD
1         GARY JIMENEZ
2       ALBERT PARDINI
3    CHRISTOPHER CHONG
4      PATRICK GARDNER
Name: EmployeeName, dtype: str

In [27]:
data['EmployeeName'].tail(5)

148649    Roy I Tillery
148650     Not provided
148651     Not provided
148652     Not provided
148653        Joe Lopez
Name: EmployeeName, dtype: str

In [29]:
#occurance of en
data['EmployeeName'].value_counts().head(5)

EmployeeName
Kevin Lee       13
Steven Lee      11
William Wong    11
Richard Lee     11
KEVIN LEE        9
Name: count, dtype: int64

In [30]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [31]:
data['JobTitle'].unique()

<StringArray>
[  'GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
                  'CAPTAIN III (POLICE DEPARTMENT)',
             'WIRE ROPE CABLE MAINTENANCE MECHANIC',
     'DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)',
                        'ASSISTANT DEPUTY CHIEF II',
               'BATTALION CHIEF, (FIRE DEPARTMENT)',
                   'DEPUTY DIRECTOR OF INVESTMENTS',
           'CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)',
 'ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)',
                      'EXECUTIVE CONTRACT EMPLOYEE',
 ...
                      'Hospital Eligibility Worker',
                                'Personnel Trainee',
                      'ACPO,JuvP, Juv Prob (SFERS)',
                        'Apprentice Cement Mason I',
                         'Marina Associate Manager',
                     'Sr Cnselor, Juv Hall (SFERS)',
                   'Forensic Toxicologist Supervis',
                                       'Conversion',
                                        'Cashier 3',
                                     'Not provided']
Length: 2159, dtype: str

In [32]:
data['JobTitle'].nunique()

2159

In [37]:
data[data['JobTitle'].str.contains("CAPTAIN",case=False)].count()

EmployeeName        552
JobTitle            552
BasePay             551
OvertimePay         552
OtherPay            552
Benefits            411
TotalPay            552
TotalPayBenefits    552
Year                552
dtype: int64

In [38]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [43]:
data[data['JobTitle'].str.contains('fire',case=False)]['EmployeeName']

4            PATRICK GARDNER
6                  ALSON LEE
8             MICHAEL MORRIS
9         JOANNE HAYES-WHITE
10             ARTHUR KENNEY
                 ...
145956      Kenneth C Farris
147556         Edward A Dunn
148021        Kari A Johnson
148209          Sheryl K Lee
148554       Lawrence F Gatt
Name: EmployeeName, Length: 5879, dtype: str

In [44]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [47]:
pd.to_numeric(data['BasePay'], errors='coerce').describe()

count    148045.000000
mean      66325.448840
std       42764.635495
min        -166.010000
25%       33588.200000
50%       65007.450000
75%       94691.050000
max      319275.010000
Name: BasePay, dtype: float64

In [50]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [53]:

import numpy as np
data['EmployeeName'].replace('Not provided',np.nan)

0            NATHANIEL FORD
1              GARY JIMENEZ
2            ALBERT PARDINI
3         CHRISTOPHER CHONG
4           PATRICK GARDNER
                ...
148649        Roy I Tillery
148650                  NaN
148651                  NaN
148652                  NaN
148653            Joe Lopez
Name: EmployeeName, Length: 148654, dtype: str

In [64]:
data.drop(data[data.isnull().sum(axis=1)== 5].index,axis=0)

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014
148650,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014

In [76]:
data.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='str')

In [88]:
numeric_basepay = pd.to_numeric(data['BasePay'], errors='coerce')
data.loc[numeric_basepay.idxmax(), 'EmployeeName']

'Gregory P Suhr'

In [98]:
# data['BasePay'] = pd.to_numeric(data['BasePay'], errors='coerce')
data.groupby('Year')['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [91]:
data.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='str')

In [96]:
data[data['JobTitle']=='ACCOUNTANT']['BasePay'].mean()

np.float64(46643.172)

In [99]:
data.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='str')

In [102]:
data['JobTitle'].value_counts()

JobTitle
Transit Operator                  7036
Special Nurse                     4389
Registered Nurse                  3736
Public Svc Aide-Public Works      2518
Police Officer 3                  2421
                                  ...
Marina Associate Manager             1
Sr Cnselor, Juv Hall (SFERS)         1
Forensic Toxicologist Supervis       1
Conversion                           1
Cashier 3                            1
Name: count, Length: 2159, dtype: int64

In [104]:
data['JobTitle'].value_counts().tail(20).

JobTitle
Civil Case Settlmnt Specialist    1
Captain, (Fire Department)        1
Public Safety Comm Tech           1
Drug Court Coordinator            1
IS Technician Assistant           1
Chief Investment Officer          1
Chief Forensic Toxicologist       1
Lieutenant (Police Department)    1
Undersheriff (SFERS)              1
Light Rail Vehicle Equip Eng      1
Sr Sprv Prob Ofc, Juv Prob        1
Administrative Hearing Sup        1
HH Mechanical Shop Sprv           1
Auto Body&Fender Wrk Asst Sprv    1
ACPO,JuvP, Juv Prob (SFERS)       1
Marina Associate Manager          1
Sr Cnselor, Juv Hall (SFERS)      1
Forensic Toxicologist Supervis    1
Conversion                        1
Cashier 3                         1
Name: count, dtype: int64