In [3]:
%pip install pandas

In [4]:
import pandas as pd

dictl = {
    'Name': ['Priyang', 'Aadhya', 'Krishna', 'Vedant', 'Parshv', 'Mittal', 'Archana'],
    'Marks': [98, 89, 99, 87, 90, 83, 99],
    'Gender': ['male', 'Female', 'Female', 'Male', 'Male', 'Female', 'Female']
}

df1 = pd.DataFrame(dictl)
df1

      Name  Marks  Gender
0  Priyang     98    male
1   Aadhya     89  Female
2  Krishna     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [5]:
df1.head()

      Name  Marks  Gender
0  Priyang     98    male
1   Aadhya     89  Female
2  Krishna     99  Female
3   Vedant     87    Male
4   Parshv     90    Male

In [5]:
df1.tail()

      Name  Marks  Gender
2  Krishna     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [6]:
df1.head(2)

      Name  Marks  Gender
0  Priyang     98    male
1   Aadhya     89  Female

In [7]:
df1.shape

(7, 3)

In [8]:
df1.shape[0]

7

In [9]:
df1.shape[1]

3

In [11]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      str
dtypes: int64(1), str(2)
memory usage: 184.0 bytes

In [14]:
df1.isnull().sum(axis=1)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

In [18]:
df1.describe(include='all')

           Name      Marks  Gender
count         7   7.000000       7
unique        7        NaN       3
top     Priyang        NaN  Female
freq          1        NaN       4
mean        NaN  92.142857     NaN
std         NaN   6.491753     NaN
min         NaN  83.000000     NaN
25%         NaN  88.000000     NaN
50%         NaN  90.000000     NaN
75%         NaN  98.500000     NaN
max         NaN  99.000000     NaN

In [21]:
df1

      Name  Marks  Gender
0  Priyang     98    male
1   Aadhya     89  Female
2  Krishna     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [24]:
df1['Gender'].nunique()

3

In [26]:
df1['Gender'].value_counts()

Gender
Female    4
Male      2
male      1
Name: count, dtype: int64

In [6]:
df1['Marks'].between(90,100)

0     True
1    False
2     True
3    False
4     True
5    False
6     True
Name: Marks, dtype: bool

In [7]:
sum(df1['Marks'].between(90,100))

4

In [12]:
df1['Marks'].mean()

np.float64(92.14285714285714)

In [14]:
df1['Marks'].max()

np.int64(98)

In [35]:
def marks(x):
    return x//2

In [36]:
df1['Half']=df1['Marks'].apply(marks)

In [37]:
df1

      Name  Marks  Gender  Half
0  Priyang     98    male    49
1   Aadhya     89  Female    44
2  Krishna     99  Female    49
3   Vedant     87    Male    43
4   Parshv     90    Male    45
5   Mittal     83  Female    41
6  Archana     99  Female    49